### ISSUE TITLE
docker-compose not using env variables

### ISSUE THREAD

**Issue by rosscdh** [edgurgel/poxa#103]
Firstly aaaawesome app. Thank you.

cant seem to start using just env vars in compose?

```
version: '3'
services:
  poxa:
    image: edgurgel/poxa
    environment:
      - PORT=8080
      - POXA_APP_KEY=my-key
      - POXA_SECRET=secret-magic-monkey
      - POXA_APP_ID=somethigsomething
    ports:
      - "8080:8080"
      - "8443:8443"
```

the poxa.conf does not make use of the env variables
