### ISSUE TITLE
trying to run poxa using ssl

### ISSUE THREAD

**Issue by AnkitRathore175** [edgurgel/poxa#147]
Hi
I m trying to configure the poxa using ssl for wss connection using below configuration in docker
but unable to connect with wss or https however ws/http working fine
FYI, ssl is configured correctly using Let’s Encrypt and all the relavant files are in priv/ssl folder
```
version: '3'
services:
  dev:
    image: edgurgel/poxa
    container_name: dev
    environment:
      - PORT=8080
      - POXA_APP_KEY=app_key
      - POXA_SECRET=app_secret
      - POXA_APP_ID=1234
      - POXA_SSL=true
      - SSL_PORT=8443
      - SSL_CACERTFILE=ca.cer
      - SSL_CERTFILE=ssl.cer
      - SSL_KEYFILE=ssl.key
    volumes:
      - ../ssl:/priv/ssl
    ports:
      - "8080:8080"
      - "8443:8443"
```
